version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:13.5-alpine
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pwd
    ports:
      - '5432:5432'
    volumes:
      - ./volume/pgdata:/var/lib/postgresql/data
    command: [ "postgres", "-c", "wal_level=logical" ]